import { Roboto } from "next/font/google";
import NavBarComponent from "@/components/navBar";
import FooterComponent from "@/components/footer";
import "./globals.css";

const inter = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
